// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsgLYhuJ54jsXAt803SzzgdfZEiEfJaTE',
    appId: '1:708845046589:web:2988847c7f2c52d13c5354',
    messagingSenderId: '708845046589',
    projectId: 'cloudymlassignment',
    authDomain: 'cloudymlassignment.firebaseapp.com',
    storageBucket: 'cloudymlassignment.appspot.com',
    measurementId: 'G-YGMNXSX17C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1iUSyJv9LdRD7MMPUqiQSGbukeF27PSg',
    appId: '1:708845046589:android:3f16d643f2fbf0a83c5354',
    messagingSenderId: '708845046589',
    projectId: 'cloudymlassignment',
    storageBucket: 'cloudymlassignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-nEFnev1SAxBOsRL1A2UBzKDxczYxNJU',
    appId: '1:708845046589:ios:ac9d6e8ed7bf1b523c5354',
    messagingSenderId: '708845046589',
    projectId: 'cloudymlassignment',
    storageBucket: 'cloudymlassignment.appspot.com',
    iosBundleId: 'com.example.cloudymlassignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-nEFnev1SAxBOsRL1A2UBzKDxczYxNJU',
    appId: '1:708845046589:ios:a7ca0f45f0b6df7e3c5354',
    messagingSenderId: '708845046589',
    projectId: 'cloudymlassignment',
    storageBucket: 'cloudymlassignment.appspot.com',
    iosBundleId: 'com.example.cloudymlassignment.RunnerTests',
  );
}
